export const popularSearchData = {
  decorationCategories: [
    "Annaprashan",
    "Anniversary Decoration",
    "Baby Shower",
    "Baby Welcome",
    "Birthday",
    "Bride to be",
    "Bride Welcome",
    "Cabana",
    "Candle Light Dinner",
    "Canopy",
    "Car Boot",
    "Ceremony",
    "Christening",
    "Christmas",
    "Cradle Ceremony",
    "Dohale Jeevan",
    "Festival",
    "First Night",
    "Flower Decor",
    "Haldi",
    "Kids Birthday",
    "Mehndi",
    "Mundan",
    "Naming Ceremony",
    "Office",
    "Proposal",
    "Romantic",
    "Room",
    "Stage",
    "Terrace",
    "Wedding Car",
  ],
  decorationServices: [
    "Decoration in Bhubaneshwar",
    "Decoration in Chandigarh",
    "Decoration in Ghaziabad",
    "Decoration in Gurgaon",
    "Decoration in Jaipur",
    "Decoration in Jamshedpur",
    "Decoration in Jodhpur",
    "Decoration in Kanpur",
    "Decoration in Lonavala",
    "Decoration in Lucknow",
    "Decoration in Nagpur",
    "Decoration in Navi Mumbai",
    "Decoration in Noida",
    "Decoration in Patna",
    "Decoration in Ranchi",
    "Decoration in Surat",
    "Decoration in Vadodara",
  ],
  cakeDeliveryCities: [
    "Agra",
    "Amritsar",
    "Aurangabad",
    "Bhopal",
    "Bhubaneswar",
    "Bilaspur",
    "Chandigarh",
    "Coimbatore",
    "Dehradun",
    "Dhanbad",
    "Faridabad",
    "Gandhinagar",
    "Ghaziabad",
    "Gorakhpur",
    "Gurgaon",
    "Guwahati",
    "Gwalior",
    "Howrah",
    "Indore",
    "Jabalpur",
    "Jaipur",
    "Jalandhar",
    "Jammu",
    "Jamshedpur",
    "Jodhpur",
    "Kanpur",
    "Kolhapur",
    "Kota",
    "Lonavala",
    "Lucknow",
    "Ludhiana",
    "Meerut",
    "Nagpur",
    "Nashik",
    "Navi Mumbai",
    "Noida",
    "Patna",
    "Prayagraj",
    "Raipur",
    "Ranchi",
    "Secunderabad",
    "Siliguri",
    "Surat",
    "Thane",
    "Udaipur",
    "Vadodara",
    "Varanasi",
    "Visakhapatnam",
  ],
  flowerDeliveryService: [
    "Flower Delivery in Delhi",
    "Flower delivery in Pune",
    "Flower delivery in Mumbai",
    "Flower delivery in Ahmedabad",
    "Flower delivery in Bangalore",
    "Flower delivery in Kolkata",
    "Flower delivery in Agra",
    "Flower delivery in Bhubaneswar",
    "Flower delivery in Gandhinagar",
    "Flower delivery in Gurgaon",
    "Flower delivery in Noida",
    "Flower delivery in Indore",
    "Flower delivery in Jabalpur",
    "Flower delivery in Jaipur",
    "Flower delivery in Lonavala",
    "Flower delivery in Lucknow",
    "Flower delivery in Ludhiana",
    "Flower delivery in Meerut",
    "Flower delivery in Nagpur",
    "Flower delivery in Nashik",
    "Flower delivery in Hyderabad",
    "Flower delivery in Surat",
    "Flower delivery in Navi Mumbai",
  ],
};
