export const dummyCityNames = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Ahmedabad",
  "Pune",
  "Jaipur",
  "Surat",
  "Kanpur",
  "Lucknow",
  "Nagpur",
  "Indore",
  "Vadodara",
  "Coimbatore",
  "Patna",
  "Agra",
  "Visakhapatnam",
  "Chandigarh",
  "Bhopal",
  "Thane",
  "Mysore",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Kochi",
  "Bhubaneswar",
  "Guwahati",
  "Jodhpur",
  "Madurai",
  "Varanasi",
  "Dehradun",
  "Amritsar"
];

export const dummyProductReviewContent = {
  _id: Array.from({ length: 16 })
    .map((_, index) => `${Math.floor(Math.random() * 10)}`)
    .join(""),
  reviews: [
    "Absolutely delicious! The best cake I've ever had.",
    "A bit too sweet for my taste, but still a good cake.",
    "The texture was perfect, and it arrived fresh.",
    "I loved the chocolate flavor, but the frosting was a bit rich.",
    "The cake was moist and flavorful. Will order again.",
    "Not impressed. The cake was dry and lacked flavor.",
    "Great presentation and taste. Perfect for our celebration.",
    "The cake was okay, but it didn't live up to the hype.",
    "My guests raved about this cake. Will definitely recommend.",
    "Beautifully decorated, but it was a bit too dense.",
    "Very good cake. It was a hit at my daughter's birthday party.",
    "The flavors were well-balanced, and the cake was soft.",
    "Overpriced for the quality. I expected better.",
    "The best part was the frosting; it was divine.",
    "The cake was delivered on time and was as described.",
    "Perfect for a special occasion. Everyone loved it.",
    "The cake was delicious, but the delivery was late.",
    "I enjoyed the cake, but the portion size was smaller than expected.",
    "Excellent cake with a great balance of flavors.",
    "I didn't like the texture; it felt a bit too crumbly.",
    "Great service and a very tasty cake. Worth every penny.",
    "The cake was fresh, but the flavor was a bit bland.",
    "Wonderful cake! Will definitely be ordering again.",
    "The decoration was impressive, but the taste was average.",
    "The cake was amazing, but I wish it had more filling."
  ],
  showReviews: 10
};

export const dummyContentReviewContent = {
  _id: Array.from({ length: 16 })
    .map((_, index) => `${Math.floor(Math.random() * 10)}`)
    .join(""),
  reviews: [
    "The gift selection is absolutely fantastic!",
    "I found the perfect gift for my sister's birthday.",
    "Loved the unique options for personalized gifts.",
    "The quality of the gifts exceeded my expectations.",
    "Everyone loved the gifts I picked from here!",
    "Such a thoughtful collection for every occasion.",
    "I was able to find something special for everyone.",
    "The personalized engraving added such a nice touch!",
    "The gift packaging was so elegant and well-done.",
    "I'm thrilled with how quickly my gift arrived.",
    "The variety of items is perfect for any celebration.",
    "My mom absolutely loved the gift I got her!",
    "They have great options for last-minute gifting.",
    "The attention to detail in the gift is outstanding.",
    "These gifts feel truly meaningful and personal.",
    "Such beautiful options for sentimental keepsakes.",
    "It's great to have so many customizable options.",
    "I was able to find a rare and unique gift for a friend.",
    "Everyone kept asking where I got their gifts from!",
    "The quality of the craftsmanship is top-notch.",
    "I'll definitely be gifting from this collection again.",
    "So happy to see eco-friendly gifting options here.",
    "These gifts made our special moments even better.",
    "I've recommended this place to all my friends!",
    "The gifts truly stand out and feel so premium."
  ],
  showReviews: 15
};
